all: output
	./output

pont: ponteiro.cpp ponteiro.o
	g++ -Wall -c ponteiro.cpp
	g++ ponteiro.o -o output
	./output

emb: embaralhar.c embaralhar.o
	gcc -c embaralhar.c
	gcc embaralhar.o -o output
	./output